sonar.projectKey=Informatica-EPS_SalUD
sonar.organization=informatica-eps


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=SalUD
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8


# Ruta a tus códigos (puedes apuntar a src, apps, etc.)
sonar.sources=arquitecturas/microservicios/apps/

# Excluir archivos que no quieres que analice (como node_modules, tests, dist)
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts, **/*.test.tsx

# Lenguajes a analizar
sonar.language=js,ts,py