version: '3.8'

services:
  backend:
    build: ./backend
    command: npm start
    restart: always
    environment:
      - DATABASE_URL=postgres://user_admin:super_password_123@db:5432/mi_base_de_datos
      - NODE_ENV=production

  frontend:
    build: ./frontend
    command: npm run build
    restart: always