events {}

http {
    # Esta es la línea mágica que arregla tus estilos
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        
        # Donde Nginx buscará los archivos compilados de React
        root /usr/share/nginx/html;
        index index.html;

        # Redirigir el tráfico interno a index.html (clave para React Router)
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}