"""add movimientos and inventario

Revision ID: c0956b71dc79
Revises: 
Create Date: 2026-05-04 05:16:50.854312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0956b71dc79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicamentos_id'), 'medicamentos', ['id'], unique=False)
    op.create_foreign_key(None, 'inventario', 'medicamentos', ['id'], ['id'])
    op.create_foreign_key(None, 'movimientos', 'medicamentos', ['id_medicamento'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimientos', type_='foreignkey')
    op.drop_constraint(None, 'inventario', type_='foreignkey')
    op.drop_index(op.f('ix_medicamentos_id'), table_name='medicamentos')
    op.drop_table('medicamentos')
    # ### end Alembic commands ###
