name: CI/CD Pipeline to Azure VM

# ¿Por qué esto? 
# Define cuándo se ejecutará el flujo. Aquí le decimos que corra automáticamente
# cada vez que alguien suba código (push) a la rama 'master' o 'main'.
on:
  push:
    branches:
      - prod

jobs:
  # ==========================================
  # FASE 1: PRUEBAS BÁSICAS (Integración)
  # ==========================================
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Puedes ajustarlo a la versión de Node que uses

      - name: Instalar dependencias del Frontend
        working-directory: ./arquitecturas/eventos/apps/frontend
        run: npm ci

      - name: Ejecutar pruebas del Frontend (Jest)
        working-directory: ./arquitecturas/eventos/apps/frontend
        run: npm run test

# --- 2. PRUEBAS DEL BACKEND PRINCIPAL (Las que van a crear) ---
      - name: Backend - Instalar
        working-directory: ./arquitecturas/eventos/apps/backend/backend
        run: npm install

      - name: Backend - Pruebas
        working-directory: ./arquitecturas/eventos/apps/backend/backend
        run: npm run test

  # ==========================================
  # FASE 2: DESPLIEGUE EN AZURE (Entrega)
  # ==========================================
  deploy:
    name: Deploy to Azure
    needs: test # IMPORTANTE: Esto obliga a que este trabajo espere a que "test" sea exitoso.
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar comandos de despliegue vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # El script que se ejecutará DENTRO de tu máquina de Azure:
          script: |
            # 1. Navegar a la carpeta donde clonaste el proyecto en tu máquina de Azure
            cd ~/SalUD/arquitecturas/eventos
            
            # Traer los últimos cambios de la rama prod
            git fetch origin prod
            git checkout prod
            git pull origin prod
            
            # 3. Navegar a la carpeta de infraestructura donde está el docker-compose
            cd infra
            
            # 4. Reconstruir las imágenes y levantar contenedores en segundo plano
            docker-compose -f docker-compose.prod.yaml down
            docker-compose -f docker-compose.prod.yaml up -d --build